if ($fieldName$!=null || (all$upperFieldName$PageEvent!=null && !all$upperFieldName$PageEvent.get$upperFieldName$List().isEmpty())){
	all$nextUpperField$PageEvent = $nextField$Service.requestAllBy$upperFieldName$Name($fieldName$==null?all$upperFieldName$PageEvent.get$upperFieldName$List().get(0).get$upperFieldName$():$fieldName$);
	$tableName$.set$nextUpperField$List(all$nextUpperField$PageEvent.get$nextUpperField$List());
}