package co.com.cybersoft.docs.persistence.domain;
import co.com.cybersoft.tables.persistence.domain.*;

import java.util.Date;


/**
 * 
 * @author Cybersystems 2014. All rights reserved.
 *
 */

public class $upperDocName$Body {

	private String id;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	$fields$
	
	$referenceFields$
	
	$gettersSetters$
}