package co.com.cybersoft.docs.persistence.domain;
import co.com.cybersoft.tables.persistence.domain.*;

import java.util.Date;


/**
 * 
 * @author Cybersystems 2014. All rights reserved.
 *
 */

public class $upperDocName$Body {

	private String id;
	
	private Boolean _enableDeletion;

	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

	public Boolean get_enableDeletion() {
		return _enableDeletion;
	}
	public void set_enableDeletion(Boolean _enableDeletion) {
		this._enableDeletion = _enableDeletion;
	}
	
	$referenceFields$
	$fields$
	
	$gettersSetters$
}