package co.com.cybersoft.core.domain;

import java.util.Date;

public class $coreDomainClass$ {
	
	$fieldDeclaration$		
	private Date dateOfCreation;
	
	private String id;
	
	private String userName;
	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Date getDateOfCreation() {
		return dateOfCreation;
	}
	public void setDateOfCreation(Date dateOfCreation) {
		this.dateOfCreation = dateOfCreation;
	}
	
	$gettersAndSetters$
	
}
