package co.com.cybersoft.$module$.docs.events.$docName$;

import co.com.cybersoft.$module$.docs.web.domain.$docName$.$upperDocName$Info;


/**
 * Event class for $upperDocName$
 * @author Cybersystems 2014. All rights reserved.
 *
 */
public class $upperDocName$Event {
	
	private $upperDocName$Info $docName$Info;
	
	public $upperDocName$Event($upperDocName$Info $docName$Info){
		this.$docName$Info=$docName$Info;
	}

	public $upperDocName$Info get$upperDocName$() {
		return $docName$Info;
	}

}