import co.com.cybersoft.persistence.repository.$tableName$.$entityName$Repository;
import co.com.cybersoft.persistence.repository.$tableName$.$entityName$CustomRepo;
import co.com.cybersoft.persistence.repository.$tableName$.$entityName$CustomRepoImpl;
import co.com.cybersoft.persistence.services.$tableName$.$entityName$PersistenceService;
import co.com.cybersoft.persistence.services.$tableName$.$entityName$PersistenceServiceImpl;
