import co.com.cybersoft.$nature$.persistence.repository.$tableName$.$entityName$Repository;
import co.com.cybersoft.$nature$.persistence.repository.$tableName$.$entityName$CustomRepo;
import co.com.cybersoft.$nature$.persistence.repository.$tableName$.$entityName$CustomRepoImpl;
import co.com.cybersoft.$nature$.persistence.services.$tableName$.$entityName$PersistenceService;
import co.com.cybersoft.$nature$.persistence.services.$tableName$.$entityName$PersistenceServiceImpl;
