package co.com.cybersoft.docsTest.persistence.domain;

import java.util.Date;


/**
 * 
 * @author Cybersystems 2014. All rights reserved.
 *
 */

public class RequisitionBody {

	private String id;
	
	private String userName;
	
	private String createdBy;

	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	$fields$
	
	$gettersSetters$	

}