Estimado $user$:

Le informamos que es necesario revisar la siguiente lista de artículos:

$itemList$

En caso de ser necesario crear un artículo, le pedimos el favor de hacerlo en la base de datos de Spark con sus campos respectivos. En caso de que un artículo ya exista le agradecemos relacionar la referencia correspondiente. En todo caso, al final de la revisión deberá informar al usuario $requestingUser$ al correo $requestingUserMail$ con las referencias finales para cada artículo solicitado.

Atentamente,
Equipo de mensajería de Spark.

P.D: por favor no responder este mensaje.