function setModificationFormValues(id){
			   var selectedRow="#"+id;
			   var link=\$("#$docName$-body-modification-form");
			   var identification="#_id";	 
			   \$(identification).val(id);
			   \$(selectedRow).find('td').each(function (i){
			   		$fieldValues$
			   });
			\$('.popup-with-form2').click();
			document.getElementById("_itemModification").focus();
			 popupVisible=true;
		   }